### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by ONeillMB1** [RausellLab/CelliD#8]
Hello Imagine friends! Congrats on the publication of this work. I would love to use the package but I am having issues installing the package both locally, as well as on our (Pasteur) servers. 

Locally, I am using a Mac with BigSur version 11.2.3 and R 3.6.3. 
```
> devtools::install_github("RausellLab/CelliD", ref = "legacy")
Downloading GitHub repo RausellLab/CelliD@legacy
Error: Failed to install 'CellID' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

> pkgbuild::check_build_tools(debug = TRUE)
Error: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
```
On our old server, with R 3.6.0 I get the folllowing:
```
[moneill@tars-submit0 ~]$ R_install_packages --git-hub RausellLab/CelliD
[1] "installing packages: RausellLab/CelliD to /pasteur/projets/policy01/evo_immuno_pop/R_3.6_scLib"
Using github PAT from envvar GITHUB_PAT
Fatal: Error in validate_signal_args(msg, type, call, .subclass): unused arguments (call, .subclass)
```
Please let me know if you have any suggestions and/or if you plan to release a binary.

**Comment by Cortalak** [comment]
Hello dear colleague from Pasteur, 

Thank you for your kind words.

I suspect the MAC installation problem is due to the fact that there's no tool to compile the source package on github.
On windows Rtools must be installed and on MAC  xcode must be installed to compile source package.
https://rstats.wtf/set-up-an-r-dev-environment.html#windows-system-prep.

It also sometimes help to install the devtools package again as some older version experience some issues with new packages.
I will try to put a binary version as soon as I'm back in office. 

As for the server I am not quite sure. It might be a fortran library related problem which is difficult to troubleshoot from my side. Can you try to install for instance the cran library quantreg `install.packages("quantreg")`? If it doesn't work in a similar manner it is certainly related to the fortran library.

**Comment by Cortalak** [comment]
By the way,
As pointed on the Readme, you need to explicitly install Seurat version 3 for R 3.5/3.6
```
remotes::install_version("rsvd", version = "1.0.2")
remotes::install_version("spatstat", version = "1.61.0")
remotes::install_version("Seurat", version = "3.2.3")
```
And then proceed to install CelliD
```
setRepositories(ind = c(1,2,3))
devtools::install_github("RausellLab/CelliD", ref = "legacy")
```
It is tedious but due to many conflict of Seurat dependencies this specific installation order must be kept.
